name: E2E Tests

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''
      date:
        description: 'Date to run the workflow'
        required: false
        default: ${{ github.event.inputs.date }}


  
  pull_request: 
    branches:
      - main

     
jobs:
  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn test "-DbrowserType=chrome" "-Dallure.results.directory=target/allure-results" "-DheadlessExecution=true" "-Dtest='RegistrationTests.FirstTestCase' "


      - name: Generate Allure Report Single File
        continue-on-error: true
        run: mvn allure:report
    
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Allure
          path: target/site/allure-maven-plugin/index.html
      
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Chrome_Linux
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn test "-DbrowserType=edge" "-Dallure.results.directory=target/allure-results" "-DheadlessExecution=false" "-Dtest='RegistrationTests.FirstTestCase' "

      - name: Generate Allure Report Single File
        continue-on-error: true
        run: mvn allure:report
    
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Allure
          path: target/site/allure-maven-plugin/index.html
      
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

